name: Integración continua para Backend en prueba de Walmart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node 
        uses: actions/setup-node@v1
        with:
          node-version: 10
        env:
          DB_URL: ${{ secrets.DB_URL }}

      - name: Crear .env file
        run: |
          touch .env
          echo DB_URL=${{ secrets.DB_URL }} >> .env
          
      - name: Limpia la integración
        run: npm ci

      - name: Dependencias
        run: npm install

      - name: Testing
        run: npm test
        
      - name: Docker Autenticación
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} registry.heroku.com --password-stdin

      - name: Docker Build
        run: docker build --file Dockerfile --build-arg DB_URL=${{ secrets.DB_URL }} --tag registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Docker Push
        run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:push web --arg DB_URL=${{ secrets.DB_URL }} --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Docker Release/Deploy
        run: HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

